package com.itext.constants;

public class PDFConstants {

	public static  final String Title= "Expense Record:-";
	public static  final String addTitle= "Expense Record PDF";
	public static  final String addSubject= "Using iText";
	public static  final String addKeywords= "Java, PDF, iText";
	public static  final String addAuthor= "IHalkhata";
	public static  final String addCreator= "IHalkhata";
	
	public static  final  String Para1= "Report generated by: ";
	public static  final  String Para2= "Created Date & Time: ";
	public static  final  String Para3= "User: ";
	public static  final  String Para4= "Report for : ";
	public static  final  String Para5= "Year: ";
	public static  final  String Para6= "Total Expense: ";
	
	public static  final String Image= "apple-logo-1.PNG";
	public static  final  String Header1= "Date";
	public static  final  String Header2= "Item Name";
	public static  final  String Header3= "Description";
	public static  final  String Header4= "Exp Amount";
	public static  final  String Header5= "Cumulative Sum";
	
	public static  final String Rs= "Rs.";
	public static  final String Data1= "date";
	public static  final String Data2= "item";
	public static  final  String Data3= "desc";
	public static  final String Data4= "amount";
	public static  final String Data5= "sum";
	
	public static  final String PieData1= "type";
	public static  final String PieData2= "amount";
	
	public static  final String PieChartTitle= "Total Expense by Item Type";
	public static  final String BarChartTitle= "Total Expense per Item Type";
	public static  final String BarChartXTitle= "Type of Expense";
	public static  final String BarChartYTitle= "Expense in Rs.";
	public static  final String BarChartBarTitle= "Expense";
	
	public static  final String NB= "NB. Rows with red coloured indicates a expense greater than ";
	
	
}
